- name: Get vpc_id
  include: lookup.yml
  when:
    - vpc_name is defined

- name: Send request to API (create VPC)
  uri:
    url: "{{ AUTH_URL_VPC }}/v1/{{ PROJECT_ID }}/vpcs"
    method: POST
    body_format: raw
    return_content: yes
    follow_redirects: "{{ uri_follow_redirects }}"
    validate_certs: "{{ uri_validate_certs }}"
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'create.json.j2')|to_json }}"
  register: vpc
  retries: "{{ uri_retries }}"
  delay: "{{ uri_delay }}"
  until: vpc.status == 200
  changed_when: false
  when:
    - not vpc_id or vpc_id is undefined
#    - vpc_name is defined

- debug:
    msg: "{{ vpc }}"
